---
- name: 'Configure Windows Exporter'
  win_template:
    src: 'config.yml.j2'
    dest: 'C:\Program Files\windows_exporter\config.yml'
  notify: Restart Windows Exporter

- name: 'Ensure Windows Exporter is running and enabled at boot'
  win_service:
    name: windows_exporter
    path: '"C:\Program Files\windows_exporter\windows_exporter.exe" --config.file="C:\Program Files\windows_exporter\config.yml"'
    dependencies:
      - 'Winmgmt'
    start_mode: delayed
    state: started
  when: not ansible_check_mode

- name: 'Ensure firewall rule for Windows Exporter is allow'
  win_firewall_rule:
    name: 'windows_exporter (HTTP )'
    description: 'Inbound rule for Windows Exporter'
    program: 'C:\Program Files\windows_exporter\windows_exporter.exe'
    localport: '{{ windows_exporter_listen_port }}'
    action: allow
    direction: in
    protocol: tcp
    profiles: 'domain,private,public'
    enabled: true
    state: present
