---
- name: 'Configure Windows Exporter'
  win_template:
    src: 'config.yml.j2'
    dest: 'C:\Program Files\windows_exporter\config.yml'
  notify: Restart Windows Exporter

- name: 'Configure web config file for Windows Exporter'
  win_template:
    src: 'web_config.yml.j2'
    dest: 'C:\Program Files\windows_exporter\web_config.yml'
  notify: Restart Windows Exporter
  when:
    - windows_exporter_tls_server_config | length or
      windows_exporter_http_server_config | length or
      windows_exporter_basic_auth_users | length

- name: 'Set arguments'
  ansible.builtin.set_fact:
    _windows_exporter_arguments: >-
      --config.file="C:\Program Files\windows_exporter\config.yml"
      {%- if windows_exporter_tls_server_config | length or windows_exporter_http_server_config | length or windows_exporter_basic_auth_users | length %}
      --web.config.file "C:\Program Files\windows_exporter\web_config.yml"
      {%- endif %}

- name: 'Ensure Windows Exporter is running and enabled at boot'
  win_service:
    name: windows_exporter
    path: '"C:\Program Files\windows_exporter\windows_exporter.exe" {{ _windows_exporter_arguments }}'
    dependencies:
      - 'Winmgmt'
    start_mode: delayed
    state: started
  when: not ansible_check_mode

- name: 'Ensure firewall rule for Windows Exporter is allow'
  win_firewall_rule:
    name: 'windows_exporter (HTTP )'
    description: 'Inbound rule for Windows Exporter'
    program: 'C:\Program Files\windows_exporter\windows_exporter.exe'
    localport: '{{ windows_exporter_listen_port }}'
    action: allow
    direction: in
    protocol: tcp
    profiles: 'domain,private,public'
    enabled: true
    state: present
